source 'https://rubygems.org'

gem 'minima', '~> 2.0'
gem 'github-pages', group: :jekyll_plugins

group :jekyll_plugins do
    gem 'jekyll-octicons'
    gem 'bootstrap', '~> 4.0.0.beta'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]